# Generated by Django 4.2.3 on 2023-08-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_de_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_de_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet')], default='ford', max_length=20),
        ),
    ]
